[build]
  command = "rm -rf src/main/js/node_modules && yarn --cwd src/main/js --frozen-lockfile &&  yarn --cwd src/main/js build"
  publish = "src/main/js/build"
[build.environment]
  NETLIFY_USE_YARN=TRUE
