openapi: 3.0.0
info:
   version: 1.0.0
   title: Membership portal
   license:
      name: Eclipse Public License - 2.0
      url: https://www.eclipse.org/legal/epl-2.0/
servers:
-  url: TBD - Internal
   description: Production endpoint for the membership portal data
tags:
-  name: Membership form
   description: Definitions related to membership form data in the database
paths:
   /membership:
      get:
         tags:
         - Membership form
         summary: Membership form list
         description: Returns a list of tracked organizations
         responses:
            200:
               description: Success
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/MembershipForms'
            500:
               description: Error while retrieving data
      put:
         tags:
         - Membership form
         summary: Membership form update
         description: Using the passed organization object, updates or inserts are made to save the data.
         requestBody:
            description: The organization to be updated or inserted into the data set.
            content:
               application/json:
                  schema:
                     $ref: '#/components/schemas/MembershipForm'
         responses:
            200:
               description: Success
            403:
               description: Unauthorized
   /membership/{id}:
      parameters:
      -  name: id
         in: path
         description: Unique ID of the membership form entry
         required: true
         schema:
            $ref: '#/components/schemas/ObjectID'
      get:
         tags:
         - Membership form
         summary: Membership form
         description: Returns a membership form entry that has a matching ID
         responses:
            200:
               description: Success
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/MembershipForm'
            500:
               description: Error while retrieving data
      delete:
         tags:
         - Membership form
         summary: Membership form delete
         description: Remove a membership form entry with the given ID
         responses:
            200:
               description: Success
            403:
               description: Unauthorized
components:
   schemas:
      ObjectID:
         description: Unique identifier for an addressable object in the API.
         type: string
         minimum: 1
      DateTime:
         type: string
         format: datetime
         description: |
            Date string in the RFC 3339 format. Example, `1990-12-31T15:59:60-08:00`.

            More on this standard can be read at https://tools.ietf.org/html/rfc3339.
      Representative:
         type: object
         properties:
            first_name:
               type: string
               description: Placeholder
            last_name:
               type: string
               description: Placeholder
            email:
               type: string
               description: Placeholder
            job_title:
               type: string
               description: Placeholder
      MembershipForms:
         type: array
         items:
            $ref: '#/components/schemas/MembershipForm'
      MembershipForm:
         type: object
         properties:
            id:
               $ref: '#/components/schemas/ObjectID'
            user_id:
               $ref: '#/components/schemas/ObjectID'
            organization:
               type: object
               properties:
                  legal_name:
                     type: string
                     description: Legal Name of the Organization
                  address:
                     type: object
                     properties:
                        street:
                           type: string
                           description: Placeholder
                        city:
                           type: string
                           description: Placeholder
                        province_state:
                           type: string
                           description: Placeholder
                        country:
                           type: string
                           description: Placeholder
                        postal_code:
                           type: string
                           description: Placeholder
                        twitter:
                           type: string
                           description: Placeholder
                  representatives:
                     type: object
                     properties:
                        company:
                           $ref: '#/components/schemas/Representative'
                           description: The direct company representative
                        marketing:
                           $ref: '#/components/schemas/Representative'
                           description: The company marketing representative
                        accounting_contact:
                           $ref: '#/components/schemas/Representative'
                           description: The company accounting contact/representative
            working_group:
               type: object
               properties:
                  name:
                     type: string
                     description: Placeholder
                  representative:
                     $ref: '#/components/schemas/Representative'
            membership_level:
               type: string
               description: Placeholder
            participation_level:
               type: string
               description: Placeholder
            effective_date:
               $ref: '#/components/schemas/DateTime'
            signing:
               type: object
               properties:
                  signing_authority:
                     type: boolean
                     description: Placeholder
                  signing_representative:
                     $ref: '#/components/schemas/Representative'
