import { formField } from './formFieldModel';

const {
  organizationName,
  street,
  city,
  provinceOrState,
  country,
  postalCode,
  twitterHandle,
  companyRepresentativeFirstName,
  companyRepresentativeLastName,
  companyRepresentativeEmail,
  marketingRepresentativeFirstName,
  marketingRepresentativeLastName,
  marketingRepresentativeEmail,
  accountingRepresentativeFirstName,
  accountingRepresentativeLastName,
  accountingRepresentativeEmail,
  membershipLevel,
  workingGroup,
  participationLevel,
  effectiveDate,
  wgRepresentativeFirstName,
  wgRepresentativeLastName,
  wgRepresentativeJobTitle,
  wgRepresentativeEmail,
  signingAuthority,
  signingAuthorityFirstName,
  signingAuthorityLastName,
  signingAuthorityJobTitile,
  signingAuthorityEmail
} = formField;

export const initialValues = {
  [organizationName.name]: "",
  [street.name]: "",
  [city.name]: "",
  [provinceOrState.name]: "",
  [country.name]: "",
  [postalCode.name]: "",
  [twitterHandle.name]: "",
  [companyRepresentativeFirstName.name]: "",
  [companyRepresentativeLastName.name]: "",
  [companyRepresentativeEmail.name]: "",
  [marketingRepresentativeFirstName.name]: "",
  [marketingRepresentativeLastName.name]: "",
  [marketingRepresentativeEmail.name]: "",
  [accountingRepresentativeFirstName.name]: "",
  [accountingRepresentativeLastName.name]: "",
  [accountingRepresentativeEmail.name]: "",
  [membershipLevel.name]: "",
  [workingGroup.name]: "",
  [participationLevel.name]: "",
  [effectiveDate.name]: null,
  [wgRepresentativeFirstName.name]: "",
  [wgRepresentativeLastName.name]: "",
  [wgRepresentativeJobTitle.name]: "",
  [wgRepresentativeEmail.name]: "",
  [signingAuthority.name]: "",
  [signingAuthorityFirstName.name]: "",
  [signingAuthorityLastName.name]: "",
  [signingAuthorityJobTitile.name]: "",
  [signingAuthorityEmail.name]: ""
};